### ISSUE TITLE
3.5: integration with stf is broken

### ISSUE THREAD

**Issue by vdelendik** [qaprosoft/carina-grid#3]
regression in comparison with hub 3.4:

21:39:50.440 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {STF_ENABLED: true, adbExecTimeout: 270000, androidInstallTimeout: 270000, app: ..., appWaitDuration: 270000, autoGrantPermissions: true, carinaTestRunId: ece13057-7e69-4ac3-a0ba-d61..., deviceName: Samsung_Galaxy_S6,Nexus_5,S..., enableVNC: true, enableVideo: true, newCommandTimeout: 180, noSign: true, platformName: android, provider: mcloud, videoName: adafc41a-fe31-4a9f-b484-d65...}
21:39:50.973 ERROR [ClientResponse.getEntity] - A message body reader for Java class com.qaprosoft.zafira.models.stf.Devices, and Java type class com.qaprosoft.zafira.models.stf.Devices, and MIME media type application/json; charset=utf-8 was not found
21:39:50.975 ERROR [ClientResponse.getEntity] - The registered message body readers compatible with the MIME media type are:
*/* ->
  com.sun.jersey.core.impl.provider.entity.FormProvider
  com.sun.jersey.core.impl.provider.entity.StringProvider
  com.sun.jersey.core.impl.provider.entity.ByteArrayProvider
  com.sun.jersey.core.impl.provider.entity.FileProvider
  com.sun.jersey.core.impl.provider.entity.InputStreamProvider
  com.sun.jersey.core.impl.provider.entity.DataSourceProvider
  com.sun.jersey.core.impl.provider.entity.XMLJAXBElementProvider$General
  com.sun.jersey.core.impl.provider.entity.ReaderProvider
  com.sun.jersey.core.impl.provider.entity.DocumentProvider
  com.sun.jersey.core.impl.provider.entity.SourceProvider$StreamSourceReader
  com.sun.jersey.core.impl.provider.entity.SourceProvider$SAXSourceReader
  com.sun.jersey.core.impl.provider.entity.SourceProvider$DOMSourceReader
  com.sun.jersey.core.impl.provider.entity.XMLRootElementProvider$General
  com.sun.jersey.core.impl.provider.entity.XMLListElementProvider$General
  com.sun.jersey.core.impl.provider.entity.XMLRootObjectProvider$General
  com.sun.jersey.core.impl.provider.entity.EntityHolderReader

21:39:50.975 INFO [STF.<init>] - STF connection established
21:39:50.975 INFO [STF.<init>] - *********************************
21:39:51.040 ERROR [ClientResponse.getEntity] - A message body reader for Java class com.qaprosoft.zafira.models.stf.Devices, and Java type class com.qaprosoft.zafira.models.stf.Devices, and MIME media type application/json; charset=utf-8 was not found
21:39:51.041 ERROR [ClientResponse.getEntity] - The registered message body readers compatible with the MIME media type are:
*/* ->
  com.sun.jersey.core.impl.provider.entity.FormProvider
  com.sun.jersey.core.impl.provider.entity.StringProvider
  com.sun.jersey.core.impl.provider.entity.ByteArrayProvider
  com.sun.jersey.core.impl.provider.entity.FileProvider
  com.sun.jersey.core.impl.provider.entity.InputStreamProvider
  com.sun.jersey.core.impl.provider.entity.DataSourceProvider
  com.sun.jersey.core.impl.provider.entity.XMLJAXBElementProvider$General
  com.sun.jersey.core.impl.provider.entity.ReaderProvider
  com.sun.jersey.core.impl.provider.entity.DocumentProvider
  com.sun.jersey.core.impl.provider.entity.SourceProvider$StreamSourceReader
  com.sun.jersey.core.impl.provider.entity.SourceProvider$SAXSourceReader
  com.sun.jersey.core.impl.provider.entity.SourceProvider$DOMSourceReader
  com.sun.jersey.core.impl.provider.entity.XMLRootElementProvider$General
  com.sun.jersey.core.impl.provider.entity.XMLListElementProvider$General
  com.sun.jersey.core.impl.provider.entity.XMLRootObjectProvider$General
  com.sun.jersey.core.impl.provider.entity.EntityHolderReader

21:39:51.043 INFO [STF.isDeviceAvailable] - Unable to get devices status HTTP status via udid: UDID
21:39:51.086 ERROR [ClientResponse.getEntity] - A message body reader for Java class com.qaprosoft.zafira.models.stf.Devices, and Java type class com.qaprosoft.zafira.models.stf.Devices, and MIME media type application/json; charset=utf-8 was not found
21:39:51.086 ERROR [ClientResponse.getEntity] - The registered message body readers compatible with the MIME media type are:
*/* ->
  com.sun.jersey.core.impl.provider.entity.FormProvider
  com.sun.jersey.core.impl.provider.entity.StringProvider
  com.sun.jersey.core.impl.provider.entity.ByteArrayProvider
  com.sun.jersey.core.impl.provider.entity.FileProvider
  com.sun.jersey.core.impl.provider.entity.InputStreamProvider
  com.sun.jersey.core.impl.provider.entity.DataSourceProvider
  com.sun.jersey.core.impl.provider.entity.XMLJAXBElementProvider$General
  com.sun.jersey.core.impl.provider.entity.ReaderProvider
  com.sun.jersey.core.impl.provider.entity.DocumentProvider
  com.sun.jersey.core.impl.provider.entity.SourceProvider$StreamSourceReader
  com.sun.jersey.core.impl.provider.entity.SourceProvider$SAXSourceReader
  com.sun.jersey.core.impl.provider.entity.SourceProvider$DOMSourceReader
  com.sun.jersey.core.impl.provider.entity.XMLRootElementProvider$General
  com.sun.jersey.core.impl.provider.entity.XMLListElementProvider$General
  com.sun.jersey.core.impl.provider.entity.XMLRootObjectProvider$General
  com.sun.jersey.core.impl.provider.entity.EntityHolderReader

**Comment by hursevich** [comment]
Fixed
